In [1]:
# Importing all the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Data injection

In [2]:
# Importing the dataset
df_initial = pd.read_csv('heart_disease.csv')

# Initial EDA

In [3]:
# Checking the information of the overall dataset
df_initial.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   9971 non-null   float64
 1   Gender                9981 non-null   str
 2   Blood Pressure        9981 non-null   float64
 3   Cholesterol Level     9970 non-null   float64
 4   Exercise Habits       9975 non-null   str
 5   Smoking               9975 non-null   str
 6   Family Heart Disease  9979 non-null   str
 7   Diabetes              9970 non-null   str
 8   BMI                   9978 non-null   float64
 9   High Blood Pressure   9974 non-null   str
 10  Low HDL Cholesterol   9975 non-null   str
 11  High LDL Cholesterol  9974 non-null   str
 12  Alcohol Consumption   7414 non-null   str
 13  Stress Level          9978 non-null   str
 14  Sleep Hours           9975 non-null   float64
 15  Sugar Consumption     9970 non-null   str
 16  Triglyceride Level    9974 non-null   float64
 17  Fasting Blood Sugar   9978 non-null   float64
 18  CRP Level             9974 non-null   float64
 19  Homocysteine Level    9980 non-null   float64
 20  Heart Disease Status  10000 non-null  str
dtypes: float64(9), str(12)
memory usage: 1.6 MB

In [4]:
# Checking the descriptive information of the numerical columns
df_initial.describe()

,Age,Blood Pressure,Cholesterol Level,BMI,Sleep Hours,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level
count,9971.000000,9981.000000,9970.000000,9978.000000,9975.000000,9974.000000,9978.000000,9974.000000,9980.000000
mean,49.296259,149.757740,225.425577,29.077269,6.991329,250.734409,120.142213,7.472201,12.456271
std,18.193970,17.572969,43.575809,6.307098,1.753195,87.067226,23.584011,4.340248,4.323426
min,18.000000,120.000000,150.000000,18.002837,4.000605,100.000000,80.000000,0.003647,5.000236
25%,34.000000,134.000000,187.000000,23.658075,5.449866,176.000000,99.000000,3.674126,8.723334
50%,49.000000,150.000000,226.000000,29.079492,7.003252,250.000000,120.000000,7.472164,12.409395
75%,65.000000,165.000000,263.000000,34.520015,8.531577,326.000000,141.000000,11.255592,16.140564
max,80.000000,180.000000,300.000000,39.996954,9.999952,400.000000,160.000000,14.997087,19.999037

In [5]:
# Checking the null values
print(df_initial.isna().sum())
print('Multiple columns with null values were found.')

Age                       29
Gender                    19
Blood Pressure            19
Cholesterol Level         30
Exercise Habits           25
Smoking                   25
Family Heart Disease      21
Diabetes                  30
BMI                       22
High Blood Pressure       26
Low HDL Cholesterol       25
High LDL Cholesterol      26
Alcohol Consumption     2586
Stress Level              22
Sleep Hours               25
Sugar Consumption         30
Triglyceride Level        26
Fasting Blood Sugar       22
CRP Level                 26
Homocysteine Level        20
Heart Disease Status       0
dtype: int64
Multiple columns with null values were found.

In [6]:
# Checking the duplicated values
print(f'{df_initial.duplicated().sum()}, duplicated values were found.')

0, duplicated values were found.

In [7]:
df_initial.head()

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,No,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No

# Data Cleaning

In [84]:
# Creating the copy of the orginal df for proper backup
df = df_initial.copy()

In [85]:
# Correcting the format of the column names
df.columns = df.columns.str.replace(' ', '_').str.strip()

In [86]:
# Cleaning the Age variable
df['Age'] = df['Age'].fillna(df['Age'].median()).astype(int)

Successfully cleaned the Age Variable

In [87]:
# Cleaning the Blood Pressure variable
df['Blood_Pressure'] = df['Blood_Pressure'].fillna(df['Blood_Pressure'].median()).astype(int)

Successfully cleaned the Blood Pressure variable

In [88]:
# Cleaning the Cholesterol Level variable
df['Cholesterol_Level'] = df['Cholesterol_Level'].fillna(df['Cholesterol_Level'].median()).astype(int)

Successfully cleaned the Cholesterol Level variable

In [89]:
# Cleaning the Gender variable
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

Successfully cleaned the Gender variable

In [90]:
# Cleaning the Excersie Habit variable
df['Exercise_Habits'] = df['Exercise_Habits'].fillna(df['Exercise_Habits'].mode()[0])

Successfully cleaned the Excersie habit variable

In [91]:
# Cleaning the smoking variable
df['Smoking'] = df['Smoking'].fillna(df['Smoking'].mode()[0])

Successfully cleaned the Smoking variable

In [92]:
# Cleaning the Family heart disease variable
df['Family_Heart_Disease'] = df['Family_Heart_Disease'].fillna(df['Family_Heart_Disease'].mode()[0])

Successfully cleaned the Family heart disease variable

In [93]:
# Cleaning the Diabetes variable
df['Diabetes'] = df['Diabetes'].fillna(df['Diabetes'].mode()[0])

Successfully cleaned the Diabetes variable

In [94]:
# Cleaning the BMI varaible
df['BMI'] = df['BMI'].fillna(df['BMI'].mode()[0]).astype(float)

In [95]:
df['BMI'] = round(df['BMI'], 1)

Successfully cleaned the BMI variable

In [96]:
# Cleaning the remaining variables
categorical_variables = {
    'High_Blood_Pressure',
    'Low_HDL_Cholesterol',
    'High_LDL_Cholesterol',
    'Alcohol_Consumption',
    'Stress_Level',
    'Sugar_Consumption'
}

continuos_variables = {
    'Sleep_Hours',
    'Triglyceride_Level',
    'Fasting_Blood_Sugar',
    'CRP_Level',
    'Homocysteine_Level',
}

# Cleaning the categorical variables
for var in categorical_variables:
    if var in df.columns:
        df[var] = df[var].fillna(df[var].mode()[0])
    else:
        print('The variables were not found.')

# Cleaning the continuos variables
for var in continuos_variables:
    if var in df.columns:
        df[var] = df[var].fillna(df[var].median())
    else:
        print('The variables were not found.')

In [97]:
df['Sleep_Hours'] = df['Sleep_Hours'].astype(float)
df['Triglyceride_Level'] = df['Triglyceride_Level'].astype(int)
df['Fasting_Blood_Sugar'] = df['Fasting_Blood_Sugar'].astype(int)
df['CRP_Level'] = round(df['CRP_Level'], 1)
df['Homocysteine_Level'] = round(df['Homocysteine_Level'], 1)

Successfully cleaned the remaining variables

# Data Analysis

I will do it later on.

# Feature Engineering

In [98]:
data = df.select_dtypes(exclude=['float', 'int'])
data.head()

,Gender,Exercise_Habits,Smoking,Family_Heart_Disease,Diabetes,High_Blood_Pressure,Low_HDL_Cholesterol,High_LDL_Cholesterol,Alcohol_Consumption,Stress_Level,Sugar_Consumption,Heart_Disease_Status
0,Male,High,Yes,Yes,No,Yes,Yes,No,High,Medium,Medium,No
1,Female,High,No,Yes,Yes,No,Yes,No,Medium,High,Medium,No
2,Male,Low,No,No,No,No,Yes,Yes,Low,Low,Low,No
3,Female,High,Yes,Yes,No,Yes,No,Yes,Low,High,High,No
4,Male,Low,Yes,Yes,Yes,Yes,No,No,Low,High,High,No

In [99]:
data['Gender'].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [100]:
# Performing encoding in the categorical variables for performing further process
# For Gender variable
df['Gender'] = df['Gender'].map({'Male': 0, 'Female':1})

In [101]:
# For Smoking, Family_Heart_Disease, Diabetes, High_Blood_Pressure, Low_HDL_Cholesterol, High_LDL_Cholesterol
Yes_No_Columns = [
    'Smoking',
    'Family_Heart_Disease',
    'Diabetes',
    'High_Blood_Pressure',
    'Low_HDL_Cholesterol',
    'High_LDL_Cholesterol'
]

map_values = {'Yes': 1, 'No': 0}
for col in Yes_No_Columns:
    df[col] = df[col].map(map_values)

In [102]:
# For Exercise_Habits, Alcohol_Consumption, Stress_Level, Sugar_Consumption
from sklearn.preprocessing import OrdinalEncoder

H_M_L_Columns = [
    'Exercise_Habits',
    'Alcohol_Consumption',
    'Stress_Level',
    'Sugar_Consumption'
]

H_M_L_Order = ['Low', 'Medium', 'High']
H_M_L_Categories = [H_M_L_Order for _ in H_M_L_Columns]
H_M_L_Encoder = OrdinalEncoder(categories=H_M_L_Categories)
H_M_L_Encoded_Array = H_M_L_Encoder.fit_transform(df[H_M_L_Columns])
df[H_M_L_Columns] = pd.DataFrame(H_M_L_Encoded_Array, columns=H_M_L_Columns, index=df.index).astype(int)

In [104]:
# For the target variable
from sklearn.preprocessing import LabelEncoder

target_encoder = LabelEncoder()
df['Heart_Disease_Status'] = target_encoder.fit_transform(df['Heart_Disease_Status'])

In [110]:
df['Sleep_Hours'] = round(df['Sleep_Hours'],1)

# Data Preprocessing

In [114]:
# Creating X and Y variables
X = df.drop(columns=['Heart_Disease_Status'])
y = df['Heart_Disease_Status']

In [115]:
# Splitting the dataframe into trainning and testing data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)